version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address :9001
    ports:
      - 127.0.0.1:${MINIO_API_PORT}:9000
      - 127.0.0.1:${MINIO_CONSOLE_PORT}:9001
    volumes:
      - ./minio-data:/data
    environment:
      # MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      # MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
